name: projet1ds3
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lecle_flutter_carousel_pro: ^0.0.3  # Vérifiez si c'est bien la dernière version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/carousel1.png
    - assets/img/carousel2.jpeg
    - assets/img/carousel3.jpg
    - assets/img/carousel4.png
    - assets/img/catbeauty.jpg
    - assets/img/CatFurniture.jpg
    - assets/img/CatLaptops.png
    - assets/img/CatPhones.png
    - assets/img/CatShoes.jpg
    - assets/img/CatWatches.jpg
